/*COLOCAR O BANCO EM USO*/
USE comaBem;

/*CRIANDO UM NOVO PERFIL DE USUARIO*/
CREATE ROLE novoPerfil;

/*CRIANDO UM NOVO USUARIO E O ADICIONANDO AO PERFIL CRIADO*/
CREATE USER Anderson IDENTIFIED BY "senhaBemForte" DEFAULT ROLE novoPerfil;

/*DEFININDO O USUARIO CRIADO PARA APENAS PODER UTILIZAR O COMANDO SELECT*/
GRANT SELECT ON comaBem.* To Anderson;

/*APOS ABRIR O WORKBENCH COM O NOVO USUARIO, FAZER UM TESTE DE SELECT*/
SELECT * FROM Produtos;
SELECT * FROM Unidades;

/*AGORA TENTAR FAZER UMA INSERÇÃO DE DADOS, VAI APRESENTAR ERRO, POIS APENAS DEFINIMOS O SELECT PARA ESSE USUARIO*/
INSERT INTO Produtos (ds_produto, vl_produto, qt_produto, cd_unidade) VALUES ("Frango", 25.00, 2, 1 );